print("*******add*******")
s={'a','b','c','d'}
s.add('e')
print(s)
print("*******to remove element*******")
s.discard('b')
print(s)
s.remove('c')
print(s)
s.pop()
print(s)
s.clear()
print(s)
s1={1,2,3}
s2={2,3,4,5}
print("*******itersection*******")
print(s1.intersection(s2))
print("*******union*******")
print(s1.union(s2))
print("*******symmentric difference*******")
print(s1.symmetric_difference(s2))
s1.update(s2)
print(s1)
print("*******convert list to set*******")
l1=[1,2,3,4,5]
s1=set(l1)
print(s1)
